openapi: 3.0.1
info:
  title: API Service
  version: 1.0.0
  description: API Service endpoints
  contact:
    email: ahmed.khaled@mahaseel.net
    name: ahmed khaled
servers:
  - url: "/"
tags:
  - name: langchain
    description: langchains APIs
paths:
  /langchain/add:
    post:
      tags:
        - langchain
      summary: Add a langchain to the database
      operationId: langchain-add
      requestBody:
        description: New user signing up
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DraftlangchainSchema"
      responses:
        "200":
          description: langchain was added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/langchainSchema"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequestSchema"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorSchema"
  /langchain/all:
    get:
      tags:
        - langchain
      summary: Get all langchains in database
      operationId: langchain-get-all
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                properties:
                  langchains:
                    type: array
                    items:
                      $ref: "#/components/schemas/langchainSchema"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorSchema"
  /langchain/id/{langchainId}:
    get:
      parameters:
        - in: path
          name: langchainId
          schema:
            type: string
          required: true
          description: ID of langchain to retrieve
      tags:
        - langchain
      summary: Retrieve a langchain by ID
      operationId: langchain-get
      responses:
        "200":
          description: langchain details
          content:
            application/json:
              schema:
                properties:
                  langchain:
                    $ref: "#/components/schemas/langchainSchema"
        "404":
          description: langchain not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorSchema"
    delete:
      parameters:
        - in: path
          name: langchainId
          schema:
            type: string
          required: true
          description: ID of langchain to remove
      tags:
        - langchain
      summary: Remove a langchain by ID
      operationId: langchain-remove
      responses:
        "204":
          description: langchain removed
        "404":
          description: langchain not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFoundErrorSchema"
  /langchain/search:
    get:
      tags:
        - langchain
      summary: Search langchains by name or author
      operationId: langchain-search
      parameters:
        - in: query
          name: name
          schema:
            type: string
            default: hitchhiker
          description: String containing full name or partial name of the langchain
        - in: query
          name: author
          schema:
            type: string
            default: douglas
          description: String containing full name or partial name of the author
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                properties:
                  langchains:
                    type: array
                    items:
                      $ref: "#/components/schemas/langchainSchema"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ServerErrorSchema"
components:
  schemas:
    BadRequestSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: 'PATH: [author] ;; MESSAGE: "author" is required'
      required:
        - error
    ServerErrorSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Internal server error
      required:
        - error
    NotFoundErrorSchema:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Item not found
      required:
        - error
    DraftlangchainSchema:
      type: object
      properties:
        name:
          type: string
          description: Name of the langchain
          example: The Hitchhiker's Guide to the Galaxy
        author:
          type: string
          description: Name of the author
          example: Douglas Adams
      required:
        - name
        - author
    langchainSchema:
      allOf:
        - $ref: "#/components/schemas/DraftlangchainSchema"
      type: object
      properties:
        _id:
          type: string
          description: MongoDB id of the document
          example: 5d7224d3b40b1a1a046697dd
        createdAt:
          type: number
          description: Created at timestamp in miliseconds
          example: 1616158942428
        updatedAt:
          type: number
          description: Updated at timestamp in miliseconds
          example: 1616158942428
      required:
        - _id
        - createdAt
        - updatedAt
